name: go test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - run: "go vet ./..."
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...    
      - run: go test -v -race -covermode atomic -coverprofile=covprofile ./...
      - run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
