name: go test
description: "Runs go test, coverage etc."
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  call-workflow:
    uses: djherbis/actions/.github/workflows/go-test.yml@main
